---
version: 2
jobs:
  build:
    working_directory: ~/reddit-mvp
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: reddit-mvp
          RAILS_ENV: test
          RACK_ENV: development
      - image: postgres:9.5
        environment:
          POSTGRES_USER: reddit-mvp   
          POSTGRES_DB: reddit-mvp_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Install bundler
      - run: gem install bundler:2.1.4

      # Bundle install dependencies
      - run: bundle install --path

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rake