    ---
version: 2
jobs:
    build:
        working_directory: ~/reddit-mvp
        docker:
            - image: cimg/ruby:2.7-node-browsers # use a tailored CircleCI docker image.
            environment:
                PGHOST: localhost
                PGUSER: reddit-mvp
                RAILS_ENV: test
            - image: postgres:9.5
            environment: 
              POSTGRES_USER: reddit-mvp
              POSTGRES_DB: reddit-mvp_test
              POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rake